# Generated by Selenium IDE
import time
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

options = Options()
#options.add_argument('--headless')
driver = webdriver.Chrome()

def get_bsb_time():
    ## MANHÃ: entre 07h30-09am > 11h55am-13pm NOITE: 17h40-22h45
    hora = datetime.now().time().strftime('%H:%M')
    hora_minuto = hora.split(':')
    hora = int(hora_minuto[0])
    minuto = int(hora_minuto[1])

    if hora >= 7 and hora < 9:
        return "Intervalo 1"
    elif hora == 9 and minuto == 0:
        return "Intervalo 1"
    elif hora >= 11 and hora < 13:
        return "Intervalo 2"
    elif hora == 13 and minuto == 0:
        return "Intervalo 2"
    elif hora >= 17 and hora < 22:
        return "Intervalo 3"
    elif hora == 22 and minuto <= 45:
        return "Intervalo 3"
    else:
        return "Fora dos intervalos especificados"

def purchase_method():

    link = 'https://nvaiacharirmao.myshopify.com/products/removedor-de-cravos-e-espinhas-lt-succao-a-vacuo'
    # Step # | name | target | value | comment
    # 1 | open | /collections/colecao-teste/products/mini-ferro-de-passar-roupa-lt%E2%84%A2 |  | 
    driver.get(link)
    # 2 | click | css=.product-form__add-button |  | 
    driver.find_element(By.XPATH, "(//button[@type='submit'])[2]").click()
    time.sleep(5)
    # 3 | click | linkText=FINALIZAR COMPRA |  | 
    driver.find_element(By.XPATH,'//a[@class="button button--primary" and @href="/cart"]').click()
    # 4 | type | id=name | Jose Alves | 
    driver.find_element(By.ID, "name").send_keys("Jose Alves")
    # 5 | type | id=email1 | julioouverney@hotmail.com | 
    driver.find_element(By.ID, "email1").send_keys("julioouverney@hotmail.com")
    # 6 | type | id=cpf | 861.621.770-33 | 
    driver.find_element(By.ID, "cpf").send_keys("861.621.770-33")
    # 7 | type | id=homephone | (00) 00000-0000 | 
    driver.find_element(By.ID, "homephone").send_keys("(00) 00000-0000")
    # 8 | click | xpath=//form[@id='form-customer']/div[3]/button |  | 
    driver.find_element(By.XPATH, "//button[contains(text(), 'Continuar')]").click()
    # 9 | type | id=zipcode | 65058-579 | 
    time.sleep(5)
    driver.find_element(By.ID, "zipcode").send_keys("65058-579")
    # 10 | type |  id=number | 2 | 
    time.sleep(5)
    driver.find_element(By.ID, "number").send_keys("2")
    # 11 | click | xpath=//form[@id='form-checkout-shipment']/div[2]/div[6]/button |  | 
    time.sleep(2)
    driver.find_element(By.CSS_SELECTOR, ".btn.btn-primary.btn-block.btn-send").click()

    time.sleep(5)
    driver.find_element(By.CSS_SELECTOR, 'button.btn.btn-primary.btn-block.btn-send.link-box-checkout[data-target=".box-payment"][data-url="https://seguro.ltinovacoes.com.br/checkout/payment"]').click()
    # 13 | click | xpath=//form/div/div[4]/label |  | 
    
    time.sleep(5)
    driver.find_element(By.XPATH, "//form/div/div[4]/label").click()
    # 14 | click | xpath=(//button[@type='submit'])[3] |  | 
    time.sleep(5)
    driver.find_element(By.XPATH, "(//button[@type=\'submit\'])[3]").click()

    driver.quit()

purchase_method()