# Generated by Selenium IDE
import time, random, pytz
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.firefox.options import Options

def get_bsb_time():
    ## MANHÃ: entre 07h30-09am > 11h55am-13pm NOITE: 17h40-22h45
    hora = datetime.now().time().strftime('%H:%M')
    hora_minuto = hora.split(':')
    hora = int(hora_minuto[0])
    minuto = int(hora_minuto[1])

    if hora >= 7 and hora < 9:
        return 0
    elif hora == 9 and minuto == 0:
        return 0
    elif hora >= 11 and hora < 13:
        return 0
    elif hora == 13 and minuto == 0:
        return 0
    elif hora >= 17 and hora < 22:
        return 0
    elif hora == 22 and minuto <= 45:
        return 0
    else:
        return 1

def visit_method():
    options = Options()
    options.binary_location = '/usr/bin/firefox'
    driver = webdriver.Firefox(options=options)

    link = 'https://nvaiacharirmao.myshopify.com'
    
    # 1 | open | /collections/colecao-teste/products/mini-ferro-de-passar-roupa-lt%E2%84%A2 |  | 
    while True:
        try:
            driver.get(link)
            break
        except:
            continue

    # Role para baixo em uma página
    driver.execute_script("window.scrollBy(0, 500);")

    # Role para cima em uma página
    driver.execute_script("window.scrollBy(0, -500);")

    dt_ci = random.randint(1, 7)
    print(f'Dt: ', dt_ci)
    hover_btn = driver.find_element(By.XPATH, ('//a[@data-collection-index=' + str(dt_ci) + ']'))
    driver.execute_script("arguments[0].click();", hover_btn)
    time.sleep(10)
    driver.quit()

def execute():
    
    bsb_interval = get_bsb_time()
    timezone = pytz.timezone('America/Sao_Paulo')
    dt_now = datetime.now(timezone)



    if bsb_interval == 0:
        rn = random.randint(10, 54)
        ts = random.randint(40, 60)

        print(dt_now)
        print(f"Qtd de visitas:",rn)
        print(f"Qtd de delay:",ts)

        for i in range(rn):
            try:
                visit_method()
                print(i + 1)
                time.sleep(ts)
                i += 1
            except:
                i -= 1
                time.sleep(60)
                continue
    else:
        rn = random.randint(2, 15) 
        ts = random.randint(30, 120)
        
        print(dt_now)
        print(f"Qtd de visitas:",rn)
        print(f"Qtd de delay:",ts)
        # exit()
        for i in range(rn):
            try:
                visit_method()
                print(i + 1)
                time.sleep(ts)
                i += 1
            except:
                i -= 1
                time.sleep(60)
                continue

execute()